---
- name: Remove hostname from 127.0.0.1
  lineinfile:
    dest: /etc/hosts
    regexp: "^(.*){{ansible_hostname}} localhost(.*)$" 
    line: '\1localhost\2'
    backrefs: yes
    state: present

- name: Add hostname to hosts files
  lineinfile:
    dest: /etc/hosts
    line: "{{ansible_enp0s8.ipv4.address}} {{ansible_hostname}}"
    state: present

- name: Install mesosphere
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm"

- name: Install mesos and marathon
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "mesos"
    - "marathon"

 
