---
- name: Install zookeper and marathon
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "mesosphere-zookeeper"
    - "marathon"

- name: Erase default mesos config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos"
    - "/etc/mesos-slave"
    - "/etc/default/mesos"
    - "/etc/default/mesos-master"
    - "/etc/default/mesos-slave"

- name: Add zookeper url for mesos
  lineinfile:
    line: "zk://localhost:2181/mesos"
    dest: "/etc/mesos-master/zk"
    state: present
    create: yes

- name: Add quorum number
  lineinfile:
    line: "1"
    dest: "/etc/mesos-master/quorum"
    state: present
    create: yes

- name: Add working directory
  lineinfile:
    line: "/var/lib/mesos"
    dest: "/etc/mesos-master/work_dir"
    state: present
    create: yes

- name: Add logging directory
  lineinfile:
    line: "/var/log/mesos"
    dest: "/etc/mesos-master/log_dir"
    state: present
    create: yes

- name: Copy acls to mesos master
  copy:
    src: "acls.json"
    dest: "/etc/mesos-master/acls"

- name: Add master url for marathon
  lineinfile:
    line: "zk://localhost:2181/mesos"
    dest: "/etc/marathon/conf/master"
    state: present
    create: yes

- name: Add zookeper url marathon
  lineinfile:
    line: "zk://localhost:2181/marathon"
    dest: "/etc/marathon/conf/zk"
    state: present
    create: yes

- name: Start zookeeper and mesos master service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - "zookeeper"
    - "mesos-master"
    - "marathon"

- name: Disable mesos slave service
  service:
    name: "mesos-slave"
    enabled: no
