---
- hosts: mesos
  roles:
    - { role: mesos }
  become: true

- hosts: mesos-master
  roles:
    - { role: mesos-master }
    - { role: spark }
    - { role: zeppelin }
  become: true

- hosts: mesos-slave
  roles:
    - { role: mesos-slave }
    - { role: spark }
  become: true
